version: '2'
services:
  nginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
  redis:
    image: redis
  socket:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "9300:9300"
